title: Gabriel Parreiras
email: gab.parreiras@gmail.com
description: >-
  DevOps Engineer
baseurl: ""
url: "https://gabrielparreiras.com"

github_username: gmpify
linkedin_username: gparreiras

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
   - Gemfile
   - Gemfile.lock
